### ISSUE TITLE
Fix CSS for auther missing when installed in fresh Rails 7 app

### ISSUE THREAD

**Issue by vrinek** [bkuhlmann/auther#3]
## Overview

After running `auther:credentials` and `auther:install` I tried logging in. I was greeted by an exception with a helpful tip on how to resolve it.

## Screenshots/Screencasts

![image](https://github.com/bkuhlmann/auther/assets/81346/64d67d47-fec0-4145-ab22-1659023b069f)

## Steps to Recreate

1. `rails new` with rails 7.0.x installed
2. follow steps to install auther
3. start the web server
4. visit `/login`

## Environment

```
❯ uname -a
Linux treznix 5.15.119 #1-NixOS SMP Wed Jun 28 08:29:53 UTC 2023 x86_64 GNU/Linux

# Actually running the app inside an Alpine container
❯ bin/run ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-musl]

❯ bin/run cat Gemfile.lock | grep -e ' rails ([0-9]'
    rails (7.0.6)
```

## Possible fix

```diff
diff --git a/app/assets/config/manifest.js b/app/assets/config/manifest.js
index b06fc42..fd24a97 100644
--- a/app/assets/config/manifest.js
+++ b/app/assets/config/manifest.js
@@ -3,3 +3,4 @@
 //= link_tree ../../javascript .js
 //= link_tree ../../../vendor/javascript .js
 //= link_tree ../builds
+//= link auther/application.css
```

**Comment by bkuhlmann** [comment]
Thanks for catching this. :bow: It seems something changed in one of the Rails releases (or I missed something in the release notes) but this is fixed in [Author 15.0.1](https://alchemists.io/projects/auther/versions). Let me know if you hit any other issues, though.
